import { AnalysisResult } from "@/types";

export const mockAnalysisResults: AnalysisResult[] = [
  {
    id: "1",
    text: "This text was generated by an AI language model. It follows patterns typical of machine-generated content, with consistent tone and structure throughout. The vocabulary usage and sentence construction are highly optimized and lack the natural variations found in human writing.",
    classification: "ai",
    confidenceScore: 92,
    highlights: [
      {
        start: 0,
        end: 39,
        reason: "Explicit self-reference to AI generation",
      },
      {
        start: 40,
        end: 120,
        reason: "Overly consistent tone and structure",
      },
      {
        start: 121,
        end: 219,
        reason: "Unnaturally optimized vocabulary and sentence construction",
      },
    ],
    suggestions: [
      "Consider adding more personal anecdotes",
      "Vary sentence structure and length",
      "Include more colloquial expressions",
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    text: "I wrote this essay last night after thinking about the topic for days. My personal experience with this subject goes back to my childhood when I first encountered it. Sometimes I struggle to find the right words, but I believe my passion for the subject comes through in my writing, even with the occasional typo or awkward phrasing that I missed during proofreading.",
    classification: "human",
    confidenceScore: 88,
    highlights: [
      {
        start: 95,
        end: 155,
        reason: "Personal anecdote and emotional context",
      },
      {
        start: 156,
        end: 250,
        reason: "Admission of writing struggles - typical human trait",
      },
    ],
    suggestions: [
      "No significant AI patterns detected",
      "Contains natural language variations",
      "Includes personal context and emotion",
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    text: "The quantum theory of fields provides a framework for understanding particle interactions at the subatomic level. This theoretical approach combines principles from quantum mechanics and special relativity to describe how particles behave. However, I've always found it fascinating how these abstract mathematical concepts can explain the physical world around us, even though I sometimes get lost in the equations when studying late at night.",
    classification: "mixed",
    confidenceScore: 65,
    highlights: [
      {
        start: 0,
        end: 182,
        reason: "Formal, textbook-like explanation - potential AI generation",
      },
      {
        start: 183,
        end: 307,
        reason: "Personal reflection and admission of difficulty - human-like element",
      },
    ],
    suggestions: [
      "First section appears AI-generated (formal, educational tone)",
      "Later section includes personal elements typical of human writing",
      "Consider reviewing the formal sections for more personal voice",
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];