import React from "react";
import { StyleSheet, Text, View, ScrollView, Image } from "react-native";
import { useRouter } from "expo-router";
import { FileText, Shield, BarChart, Zap, CheckCircle, Users, Clock } from "lucide-react-native";
import Colors from "@/constants/colors";
import Button from "@/components/Button";
import PlanCard from "@/components/PlanCard";
import { useAuth } from "@/hooks/auth-store";
import { subscriptionPlans } from "@/mocks/plans";

export default function HomeScreen() {
  const router = useRouter();
  const { isAuthenticated } = useAuth();

  const handleGetStarted = () => {
    if (isAuthenticated) {
      router.push("/(tabs)/analyze");
    } else {
      router.push("/auth/login");
    }
  };

  const handleViewDashboard = () => {
    router.push("/(tabs)/dashboard");
  };



  const handleSelectPlan = (planId: string) => {
    if (!isAuthenticated) {
      router.push("/auth/login");
    } else {
      router.push("/(tabs)/pricing");
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
      {/* Hero Section */}
      <View style={styles.heroSection}>
        <Text style={styles.heroTitle}>AI-Check</Text>
        <Text style={styles.heroSubtitle}>
          Verify if text was written by AI or human
        </Text>
        
        <View style={styles.heroImageContainer}>
          <Image
            source={{ uri: "https://images.unsplash.com/photo-1677442135968-6d89469c5f97?q=80&w=1932&auto=format&fit=crop" }}
            style={styles.heroImage}
            resizeMode="cover"
          />
        </View>
        
        <Text style={styles.heroDescription}>
          Our advanced AI detection technology helps you identify content generated by AI language models with high accuracy.
        </Text>
        
        <View style={styles.buttonContainer}>
          <Button
            title={isAuthenticated ? "Analyze Text" : "Get Started"}
            size="large"
            onPress={handleGetStarted}
            style={styles.primaryButton}
          />
          
          {isAuthenticated && (
            <Button
              title="View Dashboard"
              variant="outline"
              size="large"
              onPress={handleViewDashboard}
              style={styles.secondaryButton}
            />
          )}
        </View>
      </View>
      
      {/* Features Section */}
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Key Features</Text>
        
        <View style={styles.featuresGrid}>
          <View style={styles.featureCard}>
            <View style={[styles.featureIconContainer, { backgroundColor: Colors.light.primary + "20" }]}>
              <FileText size={24} color={Colors.light.primary} />
            </View>
            <Text style={styles.featureTitle}>Text Analysis</Text>
            <Text style={styles.featureDescription}>
              Analyze text input or uploaded documents to detect AI-generated content.
            </Text>
          </View>
          
          <View style={styles.featureCard}>
            <View style={[styles.featureIconContainer, { backgroundColor: Colors.light.success + "20" }]}>
              <Shield size={24} color={Colors.light.success} />
            </View>
            <Text style={styles.featureTitle}>High Accuracy</Text>
            <Text style={styles.featureDescription}>
              Our detection engine provides confidence scores and highlights suspicious sections.
            </Text>
          </View>
          
          <View style={styles.featureCard}>
            <View style={[styles.featureIconContainer, { backgroundColor: Colors.light.accent + "20" }]}>
              <BarChart size={24} color={Colors.light.accent} />
            </View>
            <Text style={styles.featureTitle}>Detailed Reports</Text>
            <Text style={styles.featureDescription}>
              Get comprehensive reports with visual indicators and actionable insights.
            </Text>
          </View>
          
          <View style={styles.featureCard}>
            <View style={[styles.featureIconContainer, { backgroundColor: Colors.light.warning + "20" }]}>
              <Zap size={24} color={Colors.light.warning} />
            </View>
            <Text style={styles.featureTitle}>Fast Processing</Text>
            <Text style={styles.featureDescription}>
              Quick analysis of content with immediate results and downloadable reports.
            </Text>
          </View>
        </View>
      </View>
      
      {/* How It Works Section */}
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>How It Works</Text>
        
        <View style={styles.stepsContainer}>
          <View style={styles.stepItem}>
            <View style={styles.stepNumber}>
              <Text style={styles.stepNumberText}>1</Text>
            </View>
            <View style={styles.stepContent}>
              <Text style={styles.stepTitle}>Input Your Text</Text>
              <Text style={styles.stepDescription}>
                Paste text or upload documents (PDF, DOCX, TXT) for analysis.
              </Text>
            </View>
          </View>
          
          <View style={styles.stepItem}>
            <View style={styles.stepNumber}>
              <Text style={styles.stepNumberText}>2</Text>
            </View>
            <View style={styles.stepContent}>
              <Text style={styles.stepTitle}>AI Detection Process</Text>
              <Text style={styles.stepDescription}>
                Our engine analyzes patterns, structure, and language markers.
              </Text>
            </View>
          </View>
          
          <View style={styles.stepItem}>
            <View style={styles.stepNumber}>
              <Text style={styles.stepNumberText}>3</Text>
            </View>
            <View style={styles.stepContent}>
              <Text style={styles.stepTitle}>Get Detailed Results</Text>
              <Text style={styles.stepDescription}>
                View confidence scores, highlighted sections, and download reports.
              </Text>
            </View>
          </View>
        </View>
      </View>
      
      {/* About the App Section */}
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>About AI-Check</Text>
        
        <Text style={styles.aboutDescription}>
          AI-Check is a cutting-edge platform designed to help educators, content creators, and professionals identify AI-generated text with unprecedented accuracy. Our advanced machine learning algorithms analyze writing patterns, linguistic structures, and stylistic markers to provide reliable detection results.
        </Text>
        
        <View style={styles.statsContainer}>
          <View style={styles.statItem}>
            <Users size={24} color={Colors.light.primary} />
            <Text style={styles.statNumber}>50,000+</Text>
            <Text style={styles.statLabel}>Active Users</Text>
          </View>
          
          <View style={styles.statItem}>
            <CheckCircle size={24} color={Colors.light.success} />
            <Text style={styles.statNumber}>95%</Text>
            <Text style={styles.statLabel}>Accuracy Rate</Text>
          </View>
          
          <View style={styles.statItem}>
            <Clock size={24} color={Colors.light.accent} />
            <Text style={styles.statNumber}>&lt; 5s</Text>
            <Text style={styles.statLabel}>Analysis Time</Text>
          </View>
        </View>
        
        <View style={styles.benefitsContainer}>
          <Text style={styles.benefitsTitle}>Why Choose AI-Check?</Text>
          
          <View style={styles.benefitItem}>
            <CheckCircle size={16} color={Colors.light.success} />
            <Text style={styles.benefitText}>Industry-leading accuracy with continuous model improvements</Text>
          </View>
          
          <View style={styles.benefitItem}>
            <CheckCircle size={16} color={Colors.light.success} />
            <Text style={styles.benefitText}>Support for multiple file formats and bulk processing</Text>
          </View>
          
          <View style={styles.benefitItem}>
            <CheckCircle size={16} color={Colors.light.success} />
            <Text style={styles.benefitText}>Detailed reports with highlighted suspicious sections</Text>
          </View>
          
          <View style={styles.benefitItem}>
            <CheckCircle size={16} color={Colors.light.success} />
            <Text style={styles.benefitText}>Privacy-focused with secure data handling</Text>
          </View>
          
          <View style={styles.benefitItem}>
            <CheckCircle size={16} color={Colors.light.success} />
            <Text style={styles.benefitText}>Cross-platform compatibility (Web, iOS, Android)</Text>
          </View>
        </View>
      </View>
      
      {/* Pricing Section */}
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Choose Your Plan</Text>
        <Text style={styles.pricingSubtitle}>
          Start with our free trial or choose a plan that fits your needs
        </Text>
        

        
        {/* Plans */}
        <View style={styles.plansContainer}>
          {subscriptionPlans.map((plan) => (
            <PlanCard
              key={plan.id}
              plan={plan}
              billingCycle="monthly"
              isSelected={false}
              onSelect={() => handleSelectPlan(plan.id)}
            />
          ))}
        </View>
      </View>
      
      {/* CTA Section */}
      <View style={styles.ctaSection}>
        <Text style={styles.ctaTitle}>Ready to Verify Your Content?</Text>
        <Text style={styles.ctaDescription}>
          Start with our free trial and experience the power of AI-Check.
        </Text>
        
        <Button
          title={isAuthenticated ? "Analyze Now" : "Start Free Trial"}
          size="large"
          onPress={handleGetStarted}
          style={styles.ctaButton}
        />
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  heroSection: {
    padding: 20,
    alignItems: "center",
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: Colors.light.text,
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 18,
    color: Colors.light.textSecondary,
    textAlign: "center",
    marginBottom: 24,
  },
  heroImageContainer: {
    width: "100%",
    height: 200,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 24,
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  heroDescription: {
    fontSize: 16,
    color: Colors.light.text,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
  },
  primaryButton: {
    minWidth: 150,
  },
  secondaryButton: {
    minWidth: 150,
    marginLeft: 12,
  },
  sectionContainer: {
    padding: 20,
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.light.text,
    marginBottom: 20,
  },
  featuresGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  featureCard: {
    width: "48%",
    backgroundColor: Colors.light.cardBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.light.border,
  },
  featureIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.light.text,
    marginBottom: 8,
  },
  featureDescription: {
    fontSize: 14,
    color: Colors.light.textSecondary,
    lineHeight: 20,
  },
  stepsContainer: {
    marginTop: 8,
  },
  stepItem: {
    flexDirection: "row",
    marginBottom: 24,
  },
  stepNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.light.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  stepNumberText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.light.text,
    marginBottom: 6,
  },
  stepDescription: {
    fontSize: 14,
    color: Colors.light.textSecondary,
    lineHeight: 20,
  },
  ctaSection: {
    backgroundColor: Colors.light.primary + "10",
    padding: 24,
    borderRadius: 16,
    margin: 20,
    alignItems: "center",
  },
  ctaTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.light.text,
    marginBottom: 12,
    textAlign: "center",
  },
  ctaDescription: {
    fontSize: 16,
    color: Colors.light.textSecondary,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 24,
  },
  ctaButton: {
    minWidth: 200,
  },
  aboutDescription: {
    fontSize: 16,
    color: Colors.light.text,
    lineHeight: 24,
    marginBottom: 24,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 32,
    backgroundColor: Colors.light.backgroundSecondary,
    padding: 20,
    borderRadius: 12,
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.light.text,
    marginTop: 8,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: Colors.light.textSecondary,
    textAlign: "center",
  },
  benefitsContainer: {
    marginTop: 8,
  },
  benefitsTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.light.text,
    marginBottom: 16,
  },
  benefitItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  benefitText: {
    fontSize: 14,
    color: Colors.light.text,
    marginLeft: 12,
    flex: 1,
    lineHeight: 20,
  },
  pricingSubtitle: {
    fontSize: 16,
    color: Colors.light.textSecondary,
    marginBottom: 24,
    textAlign: "center",
  },

  plansContainer: {
    marginBottom: 16,
  },
});